import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar auto-generated from the docs directory structure.
// Add new documents and they will appear here automatically.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
